NumPy Lesson 1 ✅ Arrays

NumPy Lesson 2 ⬜ Array Creation Functions

NumPy Lesson 3 ⬜ Two-Dimensional Arrays (Matrices)

NumPy Lesson 4 ⬜ Array Filtering

NumPy Lesson 5 ⬜ Mathematical Operations

NumPy Lesson 6 ⬜ Random Numbers

**NumPy (Numerical Python)** is a Python library that provides a high-performance, multidimensional array data structure and mathematical operations on those arrays. The core object is *numpy.ndarray* where ndarray = N-dimensional Array.

- Python list stores each element as a separate Python object
  - flexible but slower and uses more memory
- NumPy stores numbers in continuous memory  
  - Faster; More memory efficient; Better for math

In [5]:
import numpy as np

ages = np.array([30, 25, 40])

type(ages)    #ndarray: N-Dimensional Array

numpy.ndarray

In [4]:
ages1 = [30, 25, 40]
type(ages1)

list

In [9]:
print(ages[0])
type(ages[0])

30


numpy.int64

In [10]:
print(ages1[0])
type(ages1[0])

30


int

In [11]:
ages = np.array([30, 25, 40])
ages + 10

array([40, 35, 50])

In [14]:
[30, 25, 40] + [10]  #List

[30, 25, 40, 10]

In [15]:
ages.mean()

np.float64(31.666666666666668)

➡️ Lesson 2 – Array Creation Functions

In [16]:
import numpy as np

np.zeros(5)


array([0., 0., 0., 0., 0.])

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [20]:
np.arange(1, 6) #not include 6

array([1, 2, 3, 4, 5])

In [21]:
np.arange(0, 11, 2)   #specify step size

array([ 0,  2,  4,  6,  8, 10])

In [23]:
np.linspace(0, 10, 5)   #Create 5 equally spaced numbers between 0 and 10, specify number of points

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [24]:
np.full(5, 100)

array([100, 100, 100, 100, 100])

In [25]:
arr = np.arange(1, 6) #Check Array Size

arr.size

5

**Python List**
    Collection

**NumPy Array**
    High-performance numeric collection

**Array Creation**

zeros()
ones()
arange()
linspace()
full()

➡️ Lesson 3 – 2D Arrays (Matrices)

In [26]:
data = np.array([
    [30, 100000],
    [25,  90000],
    [40, 120000]
])

data

array([[    30, 100000],
       [    25,  90000],
       [    40, 120000]])

In [27]:
data.shape  #Check Shape


(3, 2)

In [31]:
data[0] #Access a Row

array([    30, 100000])

In [29]:
data[0,0] #Access One Value

np.int64(30)

In [32]:
data[:,0] #Select a Whole Column

array([30, 25, 40])

In [33]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

df : Table with labels

array : Raw numeric table

➡️ Lesson 4 – Array Filtering

In [34]:
import numpy as np

ages = np.array([30, 25, 40, 35, 20])

ages

array([30, 25, 40, 35, 20])

In [35]:
ages > 30 #Create a Condition

array([False, False,  True,  True, False])

In [36]:
ages[ages > 30] #Use the Condition, called Boolean Filtering, keeps only the True values.

array([40, 35])

In [37]:
ages[ages < 30]


array([25, 20])

In [38]:
ages[ages == 30]

array([30])

In [39]:
ages[ages != 30]


array([25, 40, 35, 20])

In [40]:
ages[(ages > 25) & (ages < 40)]   #Multiple Conditions (AND); alway use (condition1) & (condition2)

array([30, 35])

In [41]:
ages[(ages < 25) | (ages > 35)] #Multiple Conditions (OR)

array([40, 20])

In [42]:
data = np.array([
    [30, 100000],
    [25,  90000],
    [40, 120000]
])

data

array([[    30, 100000],
       [    25,  90000],
       [    40, 120000]])

In [43]:
data[:,0] > 30

array([False, False,  True])

In [44]:
data[data[:,0] > 30]

array([[    40, 120000]])

➡️ Lesson 5 – Mathematical Operations

In [45]:
import numpy as np

salary = np.array([
    100000,
     90000,
    120000
])

In [46]:
salary * 1.10     #Vectorized Operations, NumPy : processes the whole array at once

array([110000.,  99000., 132000.])

In [48]:
bonus = np.array([
    5000,
    4000,
    6000
])

salary + bonus    #Array + Array


array([105000,  94000, 126000])

In [50]:
salary.mean()   #Statistics

np.float64(103333.33333333333)

In [51]:
salary.max()

np.int64(120000)

In [52]:
salary.std()

np.float64(12472.191289246472)

In [53]:
data = np.array([
    [30,100000],
    [25, 90000],
    [40,120000]
])

In [54]:
data + 10   #Matrix Math

array([[    40, 100010],
       [    35,  90010],
       [    50, 120010]])

In [55]:
data[:,1]

array([100000,  90000, 120000])

In [56]:
data[:,1].mean()

np.float64(103333.33333333333)

In [57]:
salary = np.array([
100000,
 90000,
120000
])

In [59]:
import numpy as np

salary = np.array([
    100000,
     90000,
    120000
])

print(salary + 5000)

print(salary * 1.10)

print(salary.mean())

print(salary.sum())

[105000  95000 125000]
[110000.  99000. 132000.]
103333.33333333333
310000


➡️ Lesson 6 – Random Numbers

In [60]:
import numpy as np

np.random.rand()    #Generate One Random Number, 0 ≤ number < 1

0.05711814012862504

In [61]:
np.random.rand(5)   #Generate Multiple Random Numbers

array([0.510677  , 0.6753763 , 0.92870988, 0.59349345, 0.24876145])

In [62]:
np.random.randint(18, 66, 5)    #Generate Random Integers

array([30, 43, 44, 24, 53])

In [71]:
np.random.randint(    #Generate a Matrix
    1,
    100,
    (3,2)
)

array([[82, 75],
       [64, 43],
       [97, 83]])

In [86]:
np.random.seed(42)    #Set a Random Seed, To make results repeatable

In [88]:
np.random.randint(1,100,5)    #always produces the same numbers.

array([21, 83, 87, 75, 75])

In [89]:
employees = np.array([
    "David",
    "Alice",
    "Bob",
    "Carol"
])

In [93]:
np.random.choice(employees)   #Random Choice, Pick one person

np.str_('Carol')

In [95]:
np.random.choice(     #Pick two people
    employees,
    2
)

array(['Alice', 'David'], dtype='<U5')

In [96]:
rolls = np.random.randint(      #Simulation Example,Roll a die 10 times
    1,
    7,
    10
)

rolls

array([2, 4, 6, 6, 2, 4, 5, 1, 4, 2])

In [97]:
rolls.mean()

np.float64(3.6)

Phase 1: Language
--------------
- Variables
- Data Types
- If Statements
- Loops
- Functions

Phase 2: Core Containers
------------------------
- Lists
- Dictionaries

Phase 3: Objects
----------------
- Classes

Phase 4: Data Science
---------------------
- Pandas
- NumPy
- Matplotlib

Phase 5: AI
-----------
- Scikit-learn
- Hugging Face
- LLMs